# Read the Docs configuration file for CCGONOW
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen

mkdocs:
  configuration: ccgonow/mkdocs.yml

python:
  install:
    - requirements: ccgonow/docs/requirements.txt
