# Read the Docs configuration file for CCGONOW
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen
  commands:
    - pip install -r ccgonow/docs/requirements.txt
    - cd ccgonow && mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
